inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_fixme.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/test_app_templates/**/*'
    - 'vendor/**/*'
    - 'lib/hyrax/specs/**/*'

Lint/ImplicitStringConcatenation:
  Exclude:
    - 'lib/generators/qa_server/**/*'
